chore: debug pipeline
Signed-off-by: Roberto Giovanardi <roberto.giovanardi@northern.tech>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -34,15 +34,68 @@ sync:image:
     - if: '$CI_COMMIT_BRANCH == "production"'
   variables:
     TARGET_MANIFEST_FILE: "kubernetes/alvaldi-docs/alvaldi-docs-deployment.yaml"
-
-sync:image:staging:
-  extends: sync:image
   dependencies:
     - publish:image-multiplatform
+
+      #sync:image:staging:
+      #  extends: sync:image
+      #  dependencies:
+      #    - publish:image-multiplatform
+      #  rules:
+      #    - if: '$CI_COMMIT_BRANCH == "main"'
+      #  variables:
+      #    TARGET_MANIFEST_FILE: "kubernetes/staging-alvaldi-docs/staging-alvaldi-docs-deployment.yaml"
+      #  script:
+      #    # Prepare temporary workspace
+      #    - cd $(mktemp -d)
+      #    - git clone --depth 1 ${INFRA_REPOSITORY} .
+      #    - git fetch origin ${INFRA_BRANCH}:local-sync
+      #    - git checkout local-sync
+      #    - echo "DEBUG - setting new image: $"UBLISH_IMAGE_DIGEST to $TARGET_MANIFEST_FILE"
+      #    # Find and edit spec file(s)
+      #    - for file in $(echo $TARGET_MANIFEST_FILE | tr ',' '\n'); do
+      #    -   if [ ! -f "$file" ]; then
+      #    -     echo "Cannot find spec file $file for container $CI_PROJECT_NAME"
+      #    -     exit 1
+      #    -   fi
+      #    -   'sed -i -E "s#image:\s+[-_./@:a-zA-Z0-9]+#image: $PUBLISH_IMAGE_DIGEST#g" $file'
+      #    -   git add $file
+      #    - done
+      #    # Commit
+      #    - git commit -sm "[Mender CI/CD] Sync $CI_PROJECT_NAME" -m "Update $CI_PROJECT_NAME with tag $PUBLISH_IMAGE_DIGEST"
+      #    - git show
+      #    # Push (5 retries)
+      #    - for retry in $(seq 5); do
+      #    -   if git push origin local-sync:${INFRA_BRANCH}; then
+      #    -     exit 0
+      #    -   fi
+      #    -   git fetch origin ${INFRA_BRANCH}
+      #    -   git rebase origin/${INFRA_BRANCH}
+      #    - done
+      #    - exit 1
+
+sync:image:staging:
+  tags:
+    - mender-qa-worker-generic-light
   rules:
     - if: '$CI_COMMIT_BRANCH == "main"'
+  dependencies:
+    - publish:image-multiplatform
   variables:
     TARGET_MANIFEST_FILE: "kubernetes/staging-alvaldi-docs/staging-alvaldi-docs-deployment.yaml"
+  stage: sync
+  image: debian:buster
+  before_script:
+    - apt update && apt install -yyq git
+    # Prepare SSH key
+    - eval $(ssh-agent -s)
+    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
+    - mkdir -p ~/.ssh
+    - chmod 700 ~/.ssh
+    - ssh-keyscan github.com >> ~/.ssh/known_hosts
+    # Configure git
+    - git config --global user.email "mender@northern.tech"
+    - git config --global user.name "Mender Test Bot"
   script:
     # Prepare temporary workspace
     - cd $(mktemp -d)
